# Generated by Django 4.2.2 on 2023-06-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petmodel',
            old_name='Gender',
            new_name='gender',
        ),
    ]
