# Generated by Django 4.2.2 on 2023-07-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='peso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='date_vaccine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Vaccine'),
        ),
    ]
