# Generated by Django 4.2.2 on 2023-06-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_rename_gender_petmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
