# Generated by Django 4.2.2 on 2023-07-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_petmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
