# Generated by Django 4.2.2 on 2023-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_rename_img_pet_petmodel_img_pet1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet1',
            field=models.ImageField(blank=True, null=True, upload_to='pet', verbose_name='Img 1'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet2',
            field=models.ImageField(blank=True, null=True, upload_to='pet', verbose_name='Img 2'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet3',
            field=models.ImageField(blank=True, null=True, upload_to='pet', verbose_name='Img 3'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet4',
            field=models.ImageField(blank=True, null=True, upload_to='pet', verbose_name='Img 4'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet5',
            field=models.ImageField(blank=True, null=True, upload_to='pet', verbose_name='Img 5'),
        ),
    ]
