# Generated by Django 4.2.2 on 2023-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_petmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Famele', 'Famele')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
