# Generated by Django 4.2.2 on 2023-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_petmodel_img_pet1_alter_petmodel_img_pet2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet1',
            field=models.ImageField(blank=True, default='S9-05-T-PYTHON\\BackEnd\\pet\\media\\pet\\default.png', null=True, upload_to='pet/', verbose_name='Img 1'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet2',
            field=models.ImageField(blank=True, default='S9-05-T-PYTHON\\BackEnd\\pet\\media\\pet\\default.png', null=True, upload_to='pet/', verbose_name='Img 2'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet3',
            field=models.ImageField(blank=True, default='S9-05-T-PYTHON\\BackEnd\\pet\\media\\pet\\default.png', null=True, upload_to='pet/', verbose_name='Img 3'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet4',
            field=models.ImageField(blank=True, default='S9-05-T-PYTHON\\BackEnd\\pet\\media\\pet\\default.png', null=True, upload_to='pet/', verbose_name='Img 4'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet5',
            field=models.ImageField(blank=True, default='S9-05-T-PYTHON\\BackEnd\\pet\\media\\pet\\default.png', null=True, upload_to='pet/', verbose_name='Img 5'),
        ),
    ]
