# Generated by Django 4.2.2 on 2023-07-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_petmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
