# Generated by Django 4.2.2 on 2023-07-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_petmodel_img_pet1_alter_petmodel_img_pet2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet1',
            field=models.ImageField(default='pet/default.png', upload_to='pet/', verbose_name='Img 1'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet2',
            field=models.ImageField(default='pet/default.png', upload_to='pet/', verbose_name='Img 2'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet3',
            field=models.ImageField(default='pet/default.png', upload_to='pet/', verbose_name='Img 3'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet4',
            field=models.ImageField(default='pet/default.png', upload_to='pet/', verbose_name='Img 4'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='img_pet5',
            field=models.ImageField(default='pet/default.png', upload_to='pet/', verbose_name='Img 5'),
        ),
    ]
